# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=254)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('default_fee', models.DecimalField(default=100.00, decimal_places=2, max_digits=13)),
                ('contacts', models.ManyToManyField(blank=True, to='lots.Contact')),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lots.LotType'),
        ),
        migrations.AddField(
            model_name='lot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owns_lots', to='lots.Contact'),
        ),
    ]
