# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('expense', 'Expense'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue')], db_index=True, max_length=20)),
                ('contra', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Record debits as positive, credits as negative', max_digits=13)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Entry'),
        ),
    ]
