# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 03:55
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    Account = apps.get_model("ledger", "Account")

    Account(name="Cash", type="asset").save()
    Account(name="Bank", type="asset").save()
    Account(name="Fees", type="revenue").save()
    Account(name="Deposits", type="revenue").save()
    Account(name="Administrative", type="expense").save()
    Account(name="Purchases", type="expense").save()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
